version: '3.8'

services:
  # 서비스 명
  postgresql-docker:
    # 사용할 이미지
    image: 'postgres:14'
    container_name: 'postgresql-docker'
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment: 
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockertest1!
      POSTGRES_DB: docker_db
    volumes:
      - ./db:/import
  node-app:
    container_name: 'node-docker'
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   - DATABASE_URL="postgresql://docker:dockertest1!@postgresql-docker:5432/docker_db?schema=public"
    depends_on:
      - postgresql-docker
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh postgresql-docker:5432 -t 10
        npx prisma migrate dev --name initial-state
        npm test
    volumes:
      - ./:/app/